namespace: opentermsarchive
name: deployment
version: 0.0.3
readme: README.md
authors:
  - contact@opentermsarchive.org
description: >-
  This ansible collection provides roles and playbooks to deploy and manage Open
  Terms Archive collections.
license:
  - EUPL-1.2
tags: []
dependencies: {}
repository: https://github.com/OpenTermsArchive/ansible-deployment.git
documentation: https://github.com/OpenTermsArchive/ansible-deployment.git
homepage: https://github.com/OpenTermsArchive/ansible-deployment.git
issues: https://github.com/OpenTermsArchive/ansible-deployment/issues
build_ignore: []
