- name: Remove index.lock in {{ name }}
  file:
    path: "/home/{{ ansible_user }}/{{ directory }}/.git/index.lock"
    state: absent

- name: Create backup tag for {{ name }}
  command:
    cmd: git tag {{ ansible_date_time.iso8601_basic_short }}
    chdir: "/home/{{ ansible_user }}/{{ directory }}"
  tags:
    - restart
    - start
    - update

- name: Clone or update {{ name }} repository
  git:
    repo: "{{ repository }}"
    dest: "/home/{{ ansible_user }}/{{ directory }}"
    depth: 1
    force: yes
    accept_hostkey: yes
    key_file: "/home/{{ ansible_user }}/.ssh/cgus-bot-key"
  register: git_clone_app_finished
  tags:
    - setup
    - update

- name: Reset {{ name }} on origin {{ branch }}
  command:
    cmd: git reset --hard origin/{{ branch }}
    chdir: "/home/{{ ansible_user }}/{{ directory }}"
  tags:
    - restart
    - start
    - update

- name: Cleanup tags for {{ name }} (keep the last 20)
  shell: git tag -l | sort -r | tail -n +21 | xargs -n 1 -i% git tag -d %
  args:
    chdir: "/home/{{ ansible_user }}/{{ directory }}"
  tags:
    - restart
    - start
    - update
