- name: Clone Repo
  git:
    repo: "{{ repository }}"
    dest: "/home/{{ ansible_user }}/{{ app }}"
    force: yes
    accept_hostkey: yes
    key_file: "/home/{{ ansible_user }}/.ssh/cgus-bot-key"
  register: git_clone_app_finished
  tags:
    - setup
    - update

- name: Install NPM packages
  npm:
    path: "/home/{{ ansible_user }}/{{ app }}"
    unsafe_perm: yes
    production: yes
  tags:
    - setup
    - update

- name: Add .env file
  copy:
    src: .env
    dest: "/home/{{ ansible_user }}/{{ app }}/.env"
  tags:
    - setup

- name: Stop CGUs
  command: forever stop "{{ app }}"
  ignore_errors: yes
  tags:
    - restart
    - stop
    - update

- include_tasks: database.yml
  vars:
    name: CGUS-Snapshots
    repository: "{{ snapshots_repository }}"
    directory: "{{ snapshots_directory }}"
    branch: "{{ snapshots_deployed_branch }}"

- include_tasks: database.yml
  vars:
    name: CGUS-Versions
    repository: "{{ versions_repository }}"
    directory: "{{ versions_directory }}"
    branch: "{{ versions_deployed_branch }}"

- name: Start CGUs
  command:
    cmd: forever start -m 10 -a --uid "{{ app }}" -c "npm run start:scheduler:prod" ./
    chdir: "/home/{{ ansible_user }}/{{ app }}"
  environment:
    NODE_ENV: production
    PORT: "{{ app_port }}"
  tags:
    - restart
    - start
    - update
