app: cgus
repository: https://github.com/ambanum/OpenTermsArchive.git
snapshots_directory: cgus-snapshots
snapshots_repository: git@github.com:ambanum/OpenTermsArchive-snapshots.git
versions_directory: cgus-versions
versions_repository: git@github.com:ambanum/OpenTermsArchive-versions.git
