---
- name: Install common required packages
  apt:
    pkg:
    - curl
    - build-essential
    - git
    update_cache: yes
    state: latest

- name: Add the NodeSource repository to the system
  shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -

- name: Install NodeJS and Npm
  apt:
    name: nodejs
    update_cache: yes
    state: latest

- name: Update Npm to latest version
  command: npm install -g npm

- name: Install forever
  npm:
    name: forever
    global: yes
    production: yes
