name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Release type
        options:
        - patch
        - minor
        - major
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-action@users.noreply.github.com"
      - name: Install Semver
        run: npm i -g semver

      - name: Get current version
        id: get_current_version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' galaxy.yml

      - name: Bump version
        run: |
          echo "NEW_VERSION=$(semver -i $RELEASE_TYPE ${{ steps.get_current_version.outputs.result }})" >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      - name: Update changelog unreleased section with new version
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: release

      - name: Commit CHANGELOG.md and create tag
        run: |
          git add "CHANGELOG.md"
          git commit -m "Release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}

      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          galaxy_version: '${{ env.NEW_VERSION }}'

      - name: Push changes to repository
        run: git push origin && git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version changelog
        uses: superfaceai/release-changelog-action@v1
        id: get-changelog
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: read

      - name: Update GitHub release with changelog
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          body: ${{ steps.get-changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
